language: cpp
compiler:
- gcc
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
sudo: required
before_install:
- sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
install:
- sudo apt-get install cmake
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-6; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
- sudo apt-get install -y uuid-dev
script:
- mkdir bin
- cd bin
- cmake -G "Unix Makefiles" ..
- make -j
- cat /home/travis/build/blorente/antlr-4.7-cpp-cmake-base/bin/locals/antlr4cpp/src/antlr4cpp-stamp/antlr4cpp-configure-err.log
- cat /home/travis/build/blorente/antlr-4.7-cpp-cmake-base/bin/locals/antlr4cpp/src/antlr4cpp-stamp/antlr4cpp-configure-out.log
- ./test_antlr
before_deploy:
- pwd && ls
